ALTER TABLE "Group" ADD COLUMN "pointUnit" TEXT NOT NULL DEFAULT 'pt';
ALTER TABLE "Group" ADD COLUMN "laborCostPerHour" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Group" ADD COLUMN "timeUnit" TEXT NOT NULL DEFAULT 'HOUR';
